name: AyuGramDesktop CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clone the AyuGramDesktop repository with submodules, without history
      - name: Clone repository
        run: |
          git clone --recursive --depth 1 https://github.com/AyuGram/AyuGramDesktop.git tdesktop
# Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            git \
            python3 \
            python3-pip \
            qt5-default \
            libqt5svg5-dev \
            qtbase5-dev \
            qtbase5-dev-tools \
            libssl-dev \
            zlib1g-dev \
            liblz4-dev \
            libxxhash-dev \
            libjpeg-dev \
            libpng-dev \
            ffmpeg \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libswscale-dev \
            libva-dev \
            libvdpau-dev \
            libdrm-dev \
            libglib2.0-dev \
            libgtk-3-dev

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Prepare libraries
      - name: Prepare libraries
        run: |
          ./Telegram/build/prepare/linux.sh
        working-directory: tdesktop

      # Build the project using Docker
      - name: Build AyuGramDesktop
        run: |
          mkdir -p out
          cd out
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DTDESKTOP_API_ID=2040 \
            -DTDESKTOP_API_HASH=b18441a1ff607e10a989891a5462e627
          cmake --build . --config Release --parallel
        working-directory: tdesktop
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ayugramdesktop-build
          path: tdesktop/out/